### ISSUE TITLE
[Feature request] Search filename or filehash through URL

### ISSUE THREAD

**Issue by wikijm** [strontic/xcyclopedia#1]
Hi @strontic,

Thanks a lot for your project, very useful for security investigation! ❤️

Is it possible to search file with filename or filehash, directly through the URL?
Something like:
* https://strontic.github.io/xcyclopedia/search.html?q=[filename.extension]
* https://strontic.github.io/xcyclopedia/search.html?q=[filehash]

The idea is to take advantage of the functionality 'Custom search engine' on Firefox and Google Chrome, and finally add your project into https://github.com/wikijm/Awesome-Custom-Search-Engines

Regards,
WikiJM

**Comment by strontic** [comment]
Hi WikiJM!

Thanks for your feature request! The [xCyclopedia website](https://strontic.GitHub.io/xcyclopedia) does have a built-in search feature that uses client-side Google Search. However, as you've pointed out, it doesn't have a **custom** search that's accessible from URL parameters (yet).

As a *work-around*, you can use the following Google Search URL to search xCyclopedia for a particular MD5 or Filename:

`https://www.google.com/search?q=site%3Astrontic.github.io+inurl%3A[insert-MD5-or-filename-here]` 

> (note: don't include the square brackets)

However Google (and Bing) don't always index every page -- it's usually above 95% coverage though (out of the existing 15k pages).

So for a more proper solution, your request will be worked on to see if there's a straightforward way to implement, within the constraints of GitHub.io hosting. 

Have you implemented a custom search engine (with custom URL parameters), **within GitHub.io** (GitHub pages)? If so, any tips would be appreciated!

Thanks again!

**Comment by wikijm** [comment]
🎁 Greetings and Merry Christmas 🎄

Great idea to use Google Dork for searching into your project!
Understood for the gap between the data available on the search engines.

The workaround is working fine for my need, you'll see an upgrasde of my repo soon 😉 

Sadly, I didn't implemented such custom search engine within GitHub.io.
Not sure if it will work with .json and .csv file that are into .zip files.

**Comment by strontic** [comment]
Glad that works for you! Google dorking for the win. :)
