### ISSUE TITLE
strontic-xcyclopedia.json is not valid

### ISSUE THREAD

**Issue by lucasSaavedra123** [strontic/xcyclopedia#4]
Hi there! When you want to work with this json with python, _ValueError: No JSON object could be decoded_ appears. This happens because the json is not valid.

```
dos2unix strontic-xcyclopedia.json
dos2unix: Binary symbol 0x1B found at line 22163
dos2unix: Skipping binary file strontic-xcyclopedia.json
```

**Comment by strontic** [comment]
@adulau Can you check if the issue is resolved?

**Comment by strontic** [comment]
@lucasSaavedra123  Can you check if the issue is resolved?

**Comment by lucasSaavedra123** [comment]
Yes, works perfect
